### PR TITLE
Make ShapeUp compile and run on Windows

### PR DESCRIPTION
**Pull request by flowerpewpew**
[\*] Added raylib MSVC libraries
[\*] Made it compile and run
[\*] Added build scripts for generating shaders header
[\*] Full compatibility with MacOS version 

It seems that the project requires slightly older version of raygui (4.0) than shipped with raylib otherwise guiSliderDragging functionality has changed.
There are very few actual code changes, mostly for zero-initialization errors.

image

### CODE REVIEW

**Comment by Nelonn** [comment]
Use CMake instead of Visual Studio project. It will helps for users who uses CLion on wants to cross compile to windows

**Comment by darkhog** [comment]
Can you attach an exe? I really need the desktop version as I understand it has saving, as opposed to the browser version

**Comment by danielchasehooper** [comment]
Thanks for doing this! 

I don't want to add a requirement for visual studio (Just as the macOS build doesn't require xcode). I'd rather a `.bat` file. You could take this one and modify it https://github.com/EpicGamesExt/raddebugger/blob/master/build.bat

**Comment by Nelonn** [comment]
> Thanks for doing this!
> 
> I don't want to add a requirement for visual studio (Just as the macOS build doesn't require xcode). I'd rather a `.bat` file. You could take this one and modify it https://github.com/EpicGamesExt/raddebugger/blob/master/build.bat

Best variant - use CMake

**Pull request closed without merging**
